name: flutter_suncalc
description: A port of the suncalc library from https://github.com/mourner/suncalc
version: 0.1.0
author: Shaun Meredith <support@infobridge.net>
homepage: https://github.com/shanus

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


dev_dependencies:
  build_runner: ^1.10.0


# The following section is specific to Flutter.
flutter:


